# Preprocessing the real Pokemon data

by Gloria

In [40]:
import numpy as np 
import pandas as pd 
import os

### images 

getting pokemon names from the images we have so we can merge with complete dataset on pokemon names later

source: https://www.kaggle.com/datasets/arenagrenade/the-complete-pokemon-images-data-set/code

In [41]:
_root = 'real_pokemon_data/pokemon_images'
filenames = sorted(os.listdir(_root))
filenames = pd.Series(filenames)

In [42]:
filenames

0             abomasnow.png
1                  abra.png
2                 absol.png
3              accelgor.png
4      aegislash-shield.png
               ...
893             zoroark.png
894               zorua.png
895               zubat.png
896            zweilous.png
897             zygarde.png
Length: 898, dtype: object

In [43]:
image_df = pd.DataFrame()
image_df['name'] = [x[:-4] for x in filenames]
image_df

                 name
0           abomasnow
1                abra
2               absol
3            accelgor
4    aegislash-shield
..                ...
893           zoroark
894             zorua
895             zubat
896          zweilous
897           zygarde

[898 rows x 1 columns]

embedding images into base64 and adding them to the df

In [44]:
import base64

def encode_image(image_path):
    with open(image_path, 'rb') as image_file:
        return base64.b64encode(image_file.read()).decode('utf-8')

In [45]:
image_df['image_base64'] = image_df.apply(lambda row: encode_image(f'real_pokemon_data/pokemon_images/{row['name']}.png'), axis=1)

In [46]:
image_df

                 name                                       image_base64
0           abomasnow  iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...
1                abra  iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...
2               absol  iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...
3            accelgor  iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...
4    aegislash-shield  iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...
..                ...                                                ...
893           zoroark  iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...
894             zorua  iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...
895             zubat  iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...
896          zweilous  iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...
897           zygarde  iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...

[898 rows x 2 columns]

### stats dataset

source: https://www.kaggle.com/datasets/rounakbanik/pokemon

- `name`: The English name of the Pokemon
- `japanese_name`: The Original Japanese name of the Pokemon
- `pokedex_number`: The entry number of the Pokemon in the National Pokedex
- `percentage_male`: The percentage of the species that are male. Blank if the Pokemon is genderless.
- `type1`: The Primary Type of the Pokemon
- `type2`: The Secondary Type of the Pokemon
- `classification`: The Classification of the Pokemon as described by the Sun and Moon Pokedex
- `height_m`: Height of the Pokemon in metres
- `weight_kg`: The Weight of the Pokemon in kilograms
- `capture_rate`: Capture Rate of the Pokemon
- `base_egg_steps`: The number of steps required to hatch an egg of the Pokemon
- `abilities`: A stringified list of abilities that the Pokemon is capable of having
- `experience_growth`: The Experience Growth of the Pokemon
- `base_happiness`: Base Happiness of the Pokemon
- `against_?`: Eighteen features that denote the amount of damage taken against an attack of a particular type
- `hp`: The Base HP of the Pokemon
- `attack`: The Base Attack of the Pokemon
- `defense`: The Base Defense of the Pokemon
- `sp_attack`: The Base Special Attack of the Pokemon
- `sp_defense`: The Base Special Defense of the Pokemon
- `speed`: The Base Speed of the Pokemon
- `generation`: The numbered generation which the Pokemon was first introduced
- `is_legendary`: Denotes if the Pokemon is legendary.

In [47]:
stats_df = pd.read_csv('real_pokemon_data/pokemon_complete_dataset.csv')
stats_df

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
796,['Beast Boost'],0.25,1.0,0.5,2.0,0.5,1.0,2.0,0.5,1.0,...,NaN,797,107,101,61,steel,flying,999.9,7,1
797,['Beast Boost'],1.00,1.0,0.5,0.5,0.5,2.0,4.0,1.0,1.0,...,NaN,798,59,31,109,grass,steel,0.1,7,1
798,['Beast Boost'],2.00,0.5,2.0,0.5,4.0,2.0,0.5,1.0,0.5,...,NaN,799,97,53,43,dark,dragon,888.0,7,1
799,['Prism Armor'],2.00,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,NaN,800,127,89,79,psychic,NaN,230.0,7,1
800,['Soul-Heart'],0.25,0.5,0.0,1.0,0.5,1.0,2.0,0.5,1.0,...,NaN,801,130,115,65,steel,fairy,80.5,7,1

data cleaning (changing names to all lowercases)

In [48]:
stats_df['name'] = stats_df['name'].apply(str.lower)
stats_df['name']

0       bulbasaur
1         ivysaur
2        venusaur
3      charmander
4      charmeleon
          ...
796    celesteela
797       kartana
798      guzzlord
799      necrozma
800      magearna
Name: name, Length: 801, dtype: object

check pokemons that are in the dataset and have image

In [49]:
complete_df = stats_df.merge(image_df, how='inner', left_on='name', right_on='name')
complete_df

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary,image_base64
0,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,1,65,65,45,grass,poison,6.9,1,0,iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...
1,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,2,80,80,60,grass,poison,13.0,1,0,iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...
2,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,3,122,120,80,grass,poison,100.0,1,0,iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...
3,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,4,60,50,65,fire,NaN,8.5,1,0,iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...
4,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,5,80,65,80,fire,NaN,19.0,1,0,iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
748,['Beast Boost'],0.25,1.0,0.5,2.0,0.5,1.0,2.0,0.5,1.0,...,797,107,101,61,steel,flying,999.9,7,1,iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...
749,['Beast Boost'],1.00,1.0,0.5,0.5,0.5,2.0,4.0,1.0,1.0,...,798,59,31,109,grass,steel,0.1,7,1,iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...
750,['Beast Boost'],2.00,0.5,2.0,0.5,4.0,2.0,0.5,1.0,0.5,...,799,97,53,43,dark,dragon,888.0,7,1,iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...
751,['Prism Armor'],2.00,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,800,127,89,79,psychic,NaN,230.0,7,1,iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...
752,['Soul-Heart'],0.25,0.5,0.0,1.0,0.5,1.0,2.0,0.5,1.0,...,801,130,115,65,steel,fairy,80.5,7,1,iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...

we have 753 pokemons with complete stats/info and image

exporting complete df into csv

In [50]:
# complete_df.to_csv('real_pokemon_data/preprocessed_data.csv')

# file too big, maybe not a good idea to turn image into base64

## restart, new dataset

source: https://github.com/cristobalmitchell/pokedex.git

In [51]:
# had to read the file locally because there were some weird delimeter (spaces, not comma)
df = pd.read_csv('real_pokemon_data/pokemon_mitchell_data.csv')
df

,national_number,gen,english_name,japanese_name,primary_type,secondary_type,classification,percent_male,percent_female,height_m,...,evochain_1,evochain_2,evochain_3,evochain_4,evochain_5,evochain_6,gigantamax,mega_evolution,mega_evolution_alt,description
0,1,I,Bulbasaur,Fushigidane,grass,poison,Seed Pokémon,88.14,11.86,0.7,...,Level,Ivysaur,Level,Venusaur,NaN,NaN,NaN,NaN,NaN,There is a plant seed on its back right from t...
1,2,I,Ivysaur,Fushigisou,grass,poison,Seed Pokémon,88.14,11.86,1.0,...,Level,Ivysaur,Level,Venusaur,NaN,NaN,NaN,NaN,NaN,"When the bulb on its back grows large, it appe..."
2,3,I,Venusaur,Fushigibana,grass,poison,Seed Pokémon,88.14,11.86,2.0,...,Level,Ivysaur,Level,Venusaur,NaN,NaN,Gigantamax Venusaur,Mega Venusaur,NaN,Its plant blooms when it is absorbing solar en...
3,4,I,Charmander,Hitokage,fire,NaN,Lizard Pokémon,88.14,11.86,0.6,...,Level,Charmeleon,Level,Charizard,NaN,NaN,NaN,NaN,NaN,It has a preference for hot things. When it ra...
4,5,I,Charmeleon,Lizardo,fire,NaN,Flame Pokémon,88.14,11.86,1.1,...,Level,Charmeleon,Level,Charizard,NaN,NaN,NaN,NaN,NaN,"It has a barbaric nature. In battle, it whips ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
893,894,VIII,Regieleki,Regieleki,electric,NaN,Electron Pokémon,NaN,NaN,1.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,This Pokémon is a cluster of electrical energy...
894,895,VIII,Regidrago,Regidrago,dragon,NaN,Dragon Orb Pokémon,NaN,NaN,2.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,An academic theory proposes that Regidrago’s a...
895,896,VIII,Glastrier,Blizapos,ice,NaN,Wild Horse Pokémon,NaN,NaN,2.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Glastrier emits intense cold from its hooves. ...
896,897,VIII,Spectrier,Rayspos,ghost,NaN,Swift Horse Pokémon,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It probes its surroundings with all its senses...
897,898,VIII,Calyrex,Badrex,psychic,grass,King Pokémon,NaN,NaN,1.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Calyrex is a merciful Pokémon, capable of prov..."

In [52]:
df['english_name'] = df['english_name'].apply(str.lower)

In [57]:
# inner merge -> matching names 
df.merge(image_df, left_on='english_name', right_on='name', how='inner')

,national_number,gen,english_name,japanese_name,primary_type,secondary_type,classification,percent_male,percent_female,height_m,...,evochain_3,evochain_4,evochain_5,evochain_6,gigantamax,mega_evolution,mega_evolution_alt,description,name,image_base64
0,1,I,bulbasaur,Fushigidane,grass,poison,Seed Pokémon,88.14,11.86,0.7,...,Level,Venusaur,NaN,NaN,NaN,NaN,NaN,There is a plant seed on its back right from t...,bulbasaur,iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...
1,2,I,ivysaur,Fushigisou,grass,poison,Seed Pokémon,88.14,11.86,1.0,...,Level,Venusaur,NaN,NaN,NaN,NaN,NaN,"When the bulb on its back grows large, it appe...",ivysaur,iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...
2,3,I,venusaur,Fushigibana,grass,poison,Seed Pokémon,88.14,11.86,2.0,...,Level,Venusaur,NaN,NaN,Gigantamax Venusaur,Mega Venusaur,NaN,Its plant blooms when it is absorbing solar en...,venusaur,iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...
3,4,I,charmander,Hitokage,fire,NaN,Lizard Pokémon,88.14,11.86,0.6,...,Level,Charizard,NaN,NaN,NaN,NaN,NaN,It has a preference for hot things. When it ra...,charmander,iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...
4,5,I,charmeleon,Lizardo,fire,NaN,Flame Pokémon,88.14,11.86,1.1,...,Level,Charizard,NaN,NaN,NaN,NaN,NaN,"It has a barbaric nature. In battle, it whips ...",charmeleon,iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
834,894,VIII,regieleki,Regieleki,electric,NaN,Electron Pokémon,NaN,NaN,1.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,This Pokémon is a cluster of electrical energy...,regieleki,iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...
835,895,VIII,regidrago,Regidrago,dragon,NaN,Dragon Orb Pokémon,NaN,NaN,2.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,An academic theory proposes that Regidrago’s a...,regidrago,iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...
836,896,VIII,glastrier,Blizapos,ice,NaN,Wild Horse Pokémon,NaN,NaN,2.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Glastrier emits intense cold from its hooves. ...,glastrier,iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...
837,897,VIII,spectrier,Rayspos,ghost,NaN,Swift Horse Pokémon,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It probes its surroundings with all its senses...,spectrier,iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...
838,898,VIII,calyrex,Badrex,psychic,grass,King Pokémon,NaN,NaN,1.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Calyrex is a merciful Pokémon, capable of prov...",calyrex,iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...

In [68]:
outer_merge = df.merge(image_df, left_on='english_name', right_on='name', how='outer', suffixes=['', '_'], indicator=True)
outer_merge[outer_merge['_merge'] == 'right_only'].head()
# both datasets have 898 pokemons
# however the images dataset have different names that are more than the "normal" pokemon name

,national_number,gen,english_name,japanese_name,primary_type,secondary_type,classification,percent_male,percent_female,height_m,...,evochain_4,evochain_5,evochain_6,gigantamax,mega_evolution,mega_evolution_alt,description,name,image_base64,_merge
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,aegislash-shield,iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...,right_only
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,arceus-normal,iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...,right_only
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,basculin-red-striped,iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...,right_only
89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,burmy-plant,iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...,right_only
115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,cherrim-overcast,iVBORw0KGgoAAAANSUhEUgAAAdsAAAHbCAYAAACDejA0AA...,right_only

In [55]:
# using the images dataset from the same Mitchell github repo 

_root = 'real_pokemon_data/large_images'
filenames = sorted(os.listdir(_root))
filenames = pd.Series(filenames)

In [59]:
image_df2 = pd.DataFrame()
image_df2['filename'] = filenames
image_df2['pokemon_index'] = [x[:-4] for x in filenames]
image_df2['pokemon_index'] = image_df2['pokemon_index'].astype(int)

In [34]:
image_df2

    filename  pokemon_index
0    001.png              1
1    002.png              2
2    003.png              3
3    004.png              4
4    005.png              5
..       ...            ...
893  894.png            894
894  895.png            895
895  896.png            896
896  897.png            897
897  898.png            898

[898 rows x 2 columns]

In [60]:
image_df2['image_base64'] = image_df2.apply(lambda row: encode_image(f'real_pokemon_data/large_images/{row['filename']}'), axis=1)

In [61]:
image_df2

    filename  pokemon_index                                       image_base64
0    001.png              1  iVBORw0KGgoAAAANSUhEUgAAAwYAAAMGCAYAAABIxpPUAA...
1    002.png              2  iVBORw0KGgoAAAANSUhEUgAAAzwAAAM8CAYAAAHl8ZV4AA...
2    003.png              3  iVBORw0KGgoAAAANSUhEUgAABQAAAAUACAYAAAAY5P/3AA...
3    004.png              4  iVBORw0KGgoAAAANSUhEUgAAA6QAAAOkCAYAAACxv/ndAA...
4    005.png              5  iVBORw0KGgoAAAANSUhEUgAAA3YAAAN2CAYAAAHCqisbAA...
..       ...            ...                                                ...
893  894.png            894  iVBORw0KGgoAAAANSUhEUgAABQAAAAUACAYAAAAY5P/3AA...
894  895.png            895  iVBORw0KGgoAAAANSUhEUgAABQAAAAUACAYAAAAY5P/3AA...
895  896.png            896  iVBORw0KGgoAAAANSUhEUgAABQAAAAUACAYAAAAY5P/3AA...
896  897.png            897  iVBORw0KGgoAAAANSUhEUgAABQAAAAUACAYAAAAY5P/3AA...
897  898.png            898  iVBORw0KGgoAAAANSUhEUgAABQAAAAUACAYAAAAY5P/3AA...

[898 rows x 3 columns]

In [38]:
# image_df2.to_csv('processed_data.csv')